sudo: false

notifications:
  email: false

language: php

php:
#  - 5.6
  - 7.0
#  - 7.1
#  - 7.2
#  - hhvm
#  - nightly

#env:
#  - DB=mysql
#  - DB=pgsql

#services:
#  - mysql
#  - postgresql

#addons:
#  mariadb: 10.1
#  postgresql: 9.6

before_script:
  - wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer.phar

script:
  - php php-cs-fixer.phar fix --verbose --dry-run
